version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7.8
    restart: always
    networks:
      - my-network
    expose:
      - 5672
    ports:
      - 5672:5672
    logging:
      driver: json-file
  producer:
    container_name: producer
    build:
      context: .
      dockerfile: Dockerfile
    image: producer:latest
    networks:
      - my-network
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - rabbit
    logging:
      driver: json-file
networks:
  my-network:
    driver: bridge
